project_id = "hjedkkpmfzhtdzotskiv"

[functions.ai-chat]
verify_jwt = false

[functions.create-user-account]
verify_jwt = false

[functions.verify-partner-email]
verify_jwt = false

[functions.send-crm-email]
verify_jwt = false

[functions.send-contract-deposit-email]
verify_jwt = false

[functions.deposit-contract]
verify_jwt = false

[functions.process-scheduled-emails]
verify_jwt = false

[functions.send-claim-notification]
verify_jwt = false

[functions.tenant-onboarding]
verify_jwt = false

[functions.send-client-notification-email]
verify_jwt = false
